name: nox
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  nox:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest]  # [macos-latest, ubuntu-latest, windows-latest]
        python: ['3.8', '3.10', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - run: python3 --version && python --version
      - run: pip install -r requirements.txt pytest
      - run: pytest . || true  # See pytest's warnings
      - run: nox --python ${{ matrix.python }}
      # - run: nox --python ${{ matrix.python }} --report report.json && python report_to_table.py
